#! /bin/zsh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep bspswallow || bspswallow &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config merge_overlapping_monitors true
bspc config ignore_ewmh_focus          true
bspc config -m eDP-1 top_padding       24

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a MEGAsync state=floating rectangle=402x564+1508+34
bspc rule -a feh state=floating
bspc rule -a Zathura state=tiled

picom &
dunst &
feh --bg-scale $HOME/Pictures/Wallpapers/rinabg.jpg
xsetroot -cursor_name left_ptr
systemctl --user start autostart.target
pgrep -x succade > /dev/null || succade &
fcitx5 &
mconnect &
megasync &
systemctl --user --no-block start refresh_battery.service
sleep 20; pkill -RTMIN+7 volume.sh; xdo above -t $(xdo id -n root) $(xdo id -n lemonbar); bluetoothctl power on && bluetoothctl power off; pkill -RTMIN+12 notifs.sh
